version: '3'

tasks:
  up:
    cmds:
      - docker-compose up -d

  down:
    cmds:
      - docker-compose down

  phpstan:
    cmds:
      - ./vendor/bin/phpstan analyse -c phpstan.neon --memory-limit 1G

  ci:
    cmds:
      - task: phpstan
